# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/zizmorcore/zizmor-pre-commit
    rev: v1.22.0
    hooks:
      - id: zizmor
  - repo: local
    hooks:
      - id: marimo-export-notebooks
        name: Export marimo notebooks to markdown
        language: system
        files: ^content/blog/[^/]+/[^/]+\.py$
        pass_filenames: true
        entry: just marimo-export
